require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SqlTemplatesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SqlTemplate. As you add validations to SqlTemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.build(:sql_template).attributes.symbolize_keys
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SqlTemplatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all sql_templates as @sql_templates" do
      sql_template = SqlTemplate.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:sql_templates)).to eq([sql_template])
    end
  end

  describe "GET #show" do
    it "assigns the requested sql_template as @sql_template" do
      sql_template = SqlTemplate.create! valid_attributes
      get :show, {:id => sql_template.to_param}, valid_session
      expect(assigns(:sql_template)).to eq(sql_template)
    end
  end

  describe "GET #new" do
    it "assigns a new sql_template as @sql_template" do
      get :new, {}, valid_session
      expect(assigns(:sql_template)).to be_a_new(SqlTemplate)
    end
  end

  describe "GET #edit" do
    it "assigns the requested sql_template as @sql_template" do
      sql_template = SqlTemplate.create! valid_attributes
      get :edit, {:id => sql_template.to_param}, valid_session
      expect(assigns(:sql_template)).to eq(sql_template)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SqlTemplate" do
        expect {
          post :create, {:sql_template => valid_attributes}, valid_session
        }.to change(SqlTemplate, :count).by(1)
      end

      it "assigns a newly created sql_template as @sql_template" do
        post :create, {:sql_template => valid_attributes}, valid_session
        expect(assigns(:sql_template)).to be_a(SqlTemplate)
        expect(assigns(:sql_template)).to be_persisted
      end

      it "redirects to the created sql_template" do
        post :create, {:sql_template => valid_attributes}, valid_session
        expect(response).to redirect_to(SqlTemplate.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved sql_template as @sql_template" do
        post :create, {:sql_template => invalid_attributes}, valid_session
        expect(assigns(:sql_template)).to be_a_new(SqlTemplate)
      end

      it "re-renders the 'new' template" do
        post :create, {:sql_template => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sql_template" do
        sql_template = SqlTemplate.create! valid_attributes
        put :update, {:id => sql_template.to_param, :sql_template => new_attributes}, valid_session
        sql_template.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested sql_template as @sql_template" do
        sql_template = SqlTemplate.create! valid_attributes
        put :update, {:id => sql_template.to_param, :sql_template => valid_attributes}, valid_session
        expect(assigns(:sql_template)).to eq(sql_template)
      end

      it "redirects to the sql_template" do
        sql_template = SqlTemplate.create! valid_attributes
        put :update, {:id => sql_template.to_param, :sql_template => valid_attributes}, valid_session
        expect(response).to redirect_to(sql_template)
      end
    end

    context "with invalid params" do
      it "assigns the sql_template as @sql_template" do
        sql_template = SqlTemplate.create! valid_attributes
        put :update, {:id => sql_template.to_param, :sql_template => invalid_attributes}, valid_session
        expect(assigns(:sql_template)).to eq(sql_template)
      end

      it "re-renders the 'edit' template" do
        sql_template = SqlTemplate.create! valid_attributes
        put :update, {:id => sql_template.to_param, :sql_template => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested sql_template" do
      sql_template = SqlTemplate.create! valid_attributes
      expect {
        delete :destroy, {:id => sql_template.to_param}, valid_session
      }.to change(SqlTemplate, :count).by(-1)
    end

    it "redirects to the sql_templates list" do
      sql_template = SqlTemplate.create! valid_attributes
      delete :destroy, {:id => sql_template.to_param}, valid_session
      expect(response).to redirect_to(sql_templates_url)
    end
  end

end
